# Generated by Django 5.2.3 on 2025-06-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('covered', 'Covered'), ('premium', 'Premium')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.parking')),
            ],
        ),
        migrations.CreateModel(
            name='SlotPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_slots', models.PositiveIntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_pricings', to='api.location')),
                ('slot_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.slottype')),
                ('vehicle_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicletype')),
            ],
        ),
    ]
