# Generated by Django 5.2.3 on 2025-06-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='parking_id',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
