# Generated by Django 5.2.3 on 2025-06-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_location_parking_id_delete_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Default Location', max_length=100),
            preserve_default=False,
        ),
    ]
