# Generated by Django 5.2.3 on 2025-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='color',
            field=models.CharField(default='UNKNOWN', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode_of_payment',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='plate_number',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_make',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle_model',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
