# Generated by Django 5.2.3 on 2025-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
