# Generated by Django 5.2.3 on 2025-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservation_duration_hours_reservation_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_exited',
            field=models.BooleanField(default=False),
        ),
    ]
