# Generated by Django 5.2.3 on 2025-06-25 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creacreated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
