# Generated by Django 5.2.3 on 2025-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reservation_creacreated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='creacreated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
