from django.urls import path
from .views import MyTokenObtainPairView, activate_user, admin_all_reservations, admin_cancel_reservation, admin_dashboard_summary, approve_reservation, cancel_reservation, change_password, count_unread_notifications, create_checkout_session, create_reservation, deactivate_user, delete_all_reservations, list_unread_notifications, location_list_with_slot_details, locations_and_vehicle_types, mark_all_notifications_read, mark_check_in, mark_check_out, mark_reservation_as_paid, register_user, logout_user, create_location_with_pricings, update_location_with_pricings, delete_location, check_slot_availability, update_profile, user_reservations, view_profile, view_regular_users
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', logout_user, name='logout'),
    path('locations/create/', create_location_with_pricings, name='create_location'),
    path('locations/', location_list_with_slot_details, name='location-list'),
    path('locations/update/<int:location_id>/', update_location_with_pricings, name='update_location'),
    path('locations/delete/<int:location_id>/', delete_location, name='delete_location'),
    path('slots/check-availability/', check_slot_availability, name='check_slot_availability'),
    path('reservations/create/', create_reservation, name='create_reservation'),
    path('reservations/my/', user_reservations, name='user_reservations'),
    path('reservations/<int:reservation_id>/cancel/', cancel_reservation, name='cancel_reservation'),
    path('reservations/<int:reservation_id>/mark-paid/', mark_reservation_as_paid, name='mark_reservation_as_paid'),
    path('admin/deactivate-user/', deactivate_user, name='deactivate_user'),
    path('admin/activate-user/', activate_user, name='activate_user'),
    path('users/', view_regular_users, name='view-regular-users'),
    path('admin/reservations/', admin_all_reservations, name='admin-all-reservations'),
    path('admin/reservations/<int:reservation_id>/cancel/', admin_cancel_reservation, name='admin-cancel-reservation'),
    path('admin/reservations/<int:reservation_id>/check-in/', mark_check_in, name='mark-check-in'),
    path('admin/reservations/<int:reservation_id>/check-out/', mark_check_out, name='mark-check-out'),
    path('data/locations-vehicles/', locations_and_vehicle_types, name='locations-and-vehicles'),
    path('online-payments/', create_checkout_session, name='online-payment'),
    path('user/update/', update_profile, name='update_profile'),
    path('user/profile/', view_profile, name='view_profile'),
    path('user/change-password/', change_password, name='change_password'),
    path('notifications/mark-all-read/', mark_all_notifications_read, name='mark-all-notifications-read'),
    path('notifications/count/', count_unread_notifications, name='count-unread-notifications'),
    path('notifications/unread/', list_unread_notifications, name='list-unread-notifications'),
    path('delete-all-reservations/', delete_all_reservations, name='delete_all_reservations'),
    path('reservations/<int:reservation_id>/approve/', approve_reservation, name='approve-reservation'),
    path('admin/dashboard/summary/', admin_dashboard_summary, name='dashboard-summary'),
]